
# Spring properties
spring:
  application:
     name: zuul-app  # Service registers under this name

security:
  basic:
    enabled:
      false

zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:

    credits:
        serviceId: credits
        path: /app/*
        stripPrefix: false

# Discovery Server Access
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8882/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

server:
  port: 8886   # HTTP (Tomcat) port

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 4000
      circuitBreaker:
        enabled: false
  threadpool:
    default:
      coreSize: 10000

endpoints:
  info:
    enabled: true

info:
  app:
    version: "1.0.0"
    artifact: "gateway-app"
    group: "com.learning.microservices"
    lastBuildDate: "2018-01-24 22:59:41"
